spring:
  application:
    name: study

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB_HOST라는 환경 변수가 있으면 그걸 쓰고, 없으면 localhost를 써라(기본값)는 뜻입니다.
    url: jdbc:mysql://${DB_HOST:localhost}:3306/study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: study
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: update # 개발 초기에는 테이블 자동 생성을 위해 update 사용
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect